### ISSUE TITLE
Return type of the factory doesn't match passed in object type

### ISSUE THREAD

**Issue by Ocramius** [matthiasnoback/convenient-immutability#2]
As it currently stands, the factory will wrap the passed in object in an `Immutable` wrapper. While that is efficient for simplified scenarios, it will break pretty much anywhere the type system is involved.

In addition to that, no guarantees are provided for the internal state when calling any method on the object: can probably improve that too, later on.

**Comment by matthiasnoback** [comment]
Hey @Ocramius, sorry, never got back to answering you.
The idea is that there is no separate factory method. So the object will have the correct type. See the constructor that comes with the `Immutable` trait: https://github.com/matthiasnoback/convenient-immutability/blob/master/src/Immutable.php#L17
I didn't test your claim about methods changing state. Sure, if you would modify the `$_*` attributes, things will go wrong, but otherwise I assumed that the `__se()` and `__get()` methods would be used.
I never considered that use case by the way, as I just wanted to use public properties as if they were final.

**Comment by Ocramius** [comment]
@matthiasnoback closing as `invalid`: I totally missed the fact that the symbol was a `trait`. My concerns don't apply here.

**Comment by matthiasnoback** [comment]
Thanks, NP.
